apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: inhouzapp-com-tls
spec:
  secretName: inhouzapp-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: inhouzapp.com
  dnsNames:
    - inhouzapp.com
    - www.inhouzapp.com